final products = [{
  'id' : '1',
  'company':'Nike',
  'title': 'NikeShoes',
  'price': 1500.00,
  'sizes': [8,9,10,11],
  'imageUrl':'assets/images/shoes_3.png',
  'quantity' : 1,
},
{
  'id' : '2',
  'company':'Adidas',
  'title': 'Addidas Shoes',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/shoes_1.png',
  'quantity' : 1,

},
{
  'id' : '3',
  'company':'Nike',
  'title': 'NikeShoes',
  'price': 1500.00,
  'sizes': [8,9,10,11],
  'imageUrl':'assets/images/shoes_2.png',
  'quantity' : 1,

},
{
  'id' : '4',
  'company':'AirJordan',
  'title': 'AirJordan Shoes',
  'price': 1500.00,
  'sizes': [8,9,10,11],
  'imageUrl':'assets/images/shoes_4.png',
  'quantity': 1,
  
},
{
  'id' : '5',
  'company':'Nike',
  'title': 'Nike Shoes',
  'price': 1500.00,
  'sizes': [8,9,10,11],
  'imageUrl':'assets/images/shoes_3.png',
  'quantity' : 1,
},
{
  'id' : '6',
  'company':'Addidas',
  'title': 'Addidas Shoes',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/shoes_1.png',
  'quantity' : 1,
},
{
  'id' : '7',
  'company':'Nike',
  'title': 'Sport Shoe',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/bluesport.png',
  'quantity' : 1,
},
{
  'id' : '8',
  'company':'Addidas',
  'title': 'Addidasshoe',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/adidasasics.png'
},
{
  'id' : '9',
  'company':'Nike',
  'title': 'Airjordan Max',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/airjordanmax.png',
  'quantity' : 1,
},
{
  'id' : '10',
  'company':'Addidas',
  'title': 'Addidas Basics',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/adidasasics.png',
  'quantity' : 1,
},
{
  'id' : '11',
  'company':'Nike',
  'title': 'Basketball Shoe',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/basketballshoe.png',
  'quantity' : 1,
},
{
  'id' : '12',
  'company':'Nike',
  'title': 'Nike AirMax',
  'price': 2500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/nikeairmax.png',
  'quantity' : 1,
},
{
  'id' : '13',
  'company':'Nike',
  'title': 'Green Skate',
  'price': 1800.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/greenskateshoe.png',
  'quantity' : 1,
},
{
  'id' : '14',
  'company':'Nike',
  'title': 'Green Nike',
  'price': 2800.00,
  'sizes': [5,6,7,8,9,10,],
  'imageUrl':'assets/images/greennike.png',
  'quantity' : 1,
},
{
  'id' : '15',
  'company':'Bata',
  'title': 'Derby shoe',
  'price': 1000.00,
  'sizes': [6,7,8,9,10,11],
  'imageUrl':'assets/images/derbyshoe.png',
  'quantity' : 1,
},
{
  'id' : '16',
  'company':'Addidas',
  'title': 'Brownie Sport',
  'price': 3000.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/brownleathershoe.png',
  'quantity' : 1,
},
{
  'id' : '17',
  'company':'Bata',
  'title': 'Brown Leather',
  'price': 700.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/brownleather.png',
  'quantity' : 1,
},
{
  'id' : '18',
  'company':'Nike',
  'title': 'BlueSport',
  'price': 1200.00,
  'sizes': [7,8,9,],
  'imageUrl':'assets/images/bluesport.png',
  'quantity' : 1,
},
{
  'id' : '19',
  'company':'Nike',
  'title': 'Black running Shoe',
  'price': 4500.00,
  'sizes': [6,7,8,9],
  'imageUrl':'assets/images/blackrunningshoe.png',
  'quantity' : 1,
},
{
  'id' : '20',
  'company':'Bata',
  'title': 'Black Leather',
  'price': 4000.00,
  'sizes': [8,9,10,],
  'imageUrl':'assets/images/blackleather.png',
  'quantity' : 1,
},
];
