final products = [{
  'id' : '1',
  'company':'Nike',
  'title': 'NikeShoes',
  'price': 1500.00,
  'sizes': [8,9,10,11],
  'imageUrl':'assets/images/pinknike.png',
  
  'quantity' : 1,
},
{
  'id' : '2',
  'company':'Adidas',
  'title': 'Addidas Shoes',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/brownsneaker.png',
  'quantity' : 1,

},
{
  'id' : '3',
  'company':'Nike',
  'title': 'NikeShoes',
  'price': 1500.00,
  'sizes': [8,9,10,11],
  'imageUrl':'assets/images/brownnikey.png',
  'quantity' : 1,

},
{
  'id' : '4',
  'company':'AirJordan',
  'title': 'AirJordan Shoes',
  'price': 1500.00,
  'sizes': [8,9,10,11],
  'imageUrl':'assets/images/airjordan.png',
  'quantity': 1,
  
},
{
  'id' : '5',
  'company':'Nike',
  'title': 'Nike Shoes',
  'price': 1500.00,
  'sizes': [8,9,10,11],
  'imageUrl':'assets/images/nikered.png',
  'quantity' : 1,
},
{
  'id' : '6',
  'company':'Addidas',
  'title': 'Addidas Shoes',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/brownsneaker.png',
  'quantity' : 1,
},
{
  'id' : '7',
  'company':'Nike',
  'title': 'Sport Shoe',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/air.png',
  'quantity' : 1,
},
{
  'id' : '8',
  'company':'Addidas',
  'title': 'Addidasshoe',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/airblack.png'
},
{
  'id' : '9',
  'company':'Nike',
  'title': 'Airjordan Max',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/nikegreen.png',
  'quantity' : 1,
},
{
  'id' : '10',
  'company':'Addidas',
  'title': 'Addidas Basics',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/airblack.png',
  'quantity' : 1,
},
{
  'id' : '11',
  'company':'Bata',
  'title': 'Bata Premium',
  'price': 1500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/batapremium.png',
  'quantity' : 1,
},
{
  'id' : '12',
  'company':'Nike',
  'title': 'Nike brown',
  'price': 2500.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/brownnikey.png',
  'quantity' : 1,
},
{
  'id' : '13',
  'company':'Nike',
  'title': 'Green Skate',
  'price': 1800.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/nikegreen.png',
  'quantity' : 1,
},
{
  'id' : '14',
  'company':'Nike',
  'title': 'Pink Nike',
  'price': 2800.00,
  'sizes': [5,6,7,8,9,10,],
  'imageUrl':'assets/images/pinknike.png',
  'quantity' : 1,
},
{
  'id' : '15',
  'company':'Puma',
  'title': 'Converse',
  'price': 1000.00,
  'sizes': [6,7,8,9,10,11],
  'imageUrl':'assets/images/pumaconverse.png',
  'quantity' : 1,
},
{
  'id' : '16',
  'company':'Addidas',
  'title': 'Brownie Sport',
  'price': 3000.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/brownsneaker.png',
  'quantity' : 1,
},
{
  'id' : '17',
  'company':'Nike',
  'title': 'Red Nike',
  'price': 700.00,
  'sizes': [6,7,8,9,10,],
  'imageUrl':'assets/images/nikered.png',
  'quantity' : 1,
},
{
  'id' : '18',
  'company':'Nike',
  'title': 'BlueSport',
  'price': 1200.00,
  'sizes': [7,8,9,],
  'imageUrl':'assets/images/air.png',
  'quantity' : 1,
},
{
  'id' : '19',
  'company':'Nike',
  'title': 'Black running Shoe',
  'price': 4500.00,
  'sizes': [6,7,8,9],
  'imageUrl':'assets/images/airjordan.png',
  'quantity' : 1,
},
{
  'id' : '20',
  'company':'Bata',
  'title': 'Black Leather',
  'price': 4000.00,
  'sizes': [8,9,10,],
  'imageUrl':'assets/images/airblack.png',
  'quantity' : 1,
},
];
